version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
- package-ecosystem: github-actions
  directories:
    - /.github/workflows
  schedule:
    interval: weekly